
export const jwtConstants = {
  secret: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InR3b0BnbWFpbC5jb20iLCJzdWIiOjIsImlhdCI6MTc1OTIzOTQwNywiZXhwIjoxNzU5ODQ0MjA3fQ.Sa8TXo7_J9_Y_KkoBgRYR4xAKFhfHb9OGfxaRN3wRHs',
};
